apiVersion: v1
kind: Secret
metadata:
  name: analytics-service-secrets
  namespace: analytics-service
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "xxxxxxxxxxxxxxxxxxxxxxx"
  AWS_SECRET_ACCESS_KEY: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"