apiVersion: v1
kind: Secret
metadata:
  name: analytics-service-secrets
  namespace: analytics-service
type: Opaque
stringData:
  ACCESS_KEY_ID: "xxxxxxxxxxxxxxxxxxxxxxx"
  SECRET_ACCESS_KEY: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"